### PR TITLE
Update nunjucks to latest version to  fix engine version for Node v11.1

### PR DESCRIPTION
**Pull request by omarkhatibco**
See https://github.com/mozilla/nunjucks/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by electerious** [comment]
👍

**Comment by omarkhatibco** [comment]
Hi @electerious 
can you push the update to NPM please ?

**Comment by electerious** [comment]
Changing `^3.1.2` to `^3.1.4` is normally not required. `^` tells npm that it should install a version greater or equal to `3.1.2` and less than `4.0.0`. When your npm or yarn is installing `3.1.2` then you should update your npm or yarn lockfile. They might force you to use an older version. An update of this module isn't required.

**Comment by omarkhatibco** [comment]
Thanks for explaining

**Pull request merged**
